spring:
    profiles:
        include: 'common'
    datasource:
        url : jdbc:mysql://localhost:3306/springboot?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username : root
        password : root
        driver-class-name : com.mysql.jdbc.Driver
        initialize: true
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        show-sql: false
        generate-ddl: true
        hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

auth:
    user:
        name: user
        password: 12345
    jws:
        code: setCodeHere
